import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";
import { parse } from "protobufjs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const sourcePath = join(root, "proto", "svc.proto");
const outputPaths = [
  join(root, "shared", "src", "generated", "svc-proto.ts"),
] as const;
const checkOnly = process.argv.includes("--check");

function normalizeNewlines(value: string): string {
  return value.replace(/\r\n/g, "\n").replace(/\r/g, "\n");
}

function renderModule(protoSource: string): string {
  const normalized = normalizeNewlines(protoSource).trimEnd() + "\n";
  const digest = createHash("sha256").update(normalized).digest("hex");

  return `// AUTO-GENERATED by scripts/generate-proto.ts. DO NOT EDIT.
// Source: proto/svc.proto
// SHA-256: ${digest}

export const PROTO_DEFINITION_SHA256 = "${digest}" as const;
export const PROTO_DEFINITION = ${JSON.stringify(normalized)};
`;
}

const protoSource = await readFile(sourcePath, "utf8");
parse(protoSource, { keepCase: true });
const expected = renderModule(protoSource);
const drifted: string[] = [];

for (const outputPath of outputPaths) {
  let current = "";
  try {
    current = normalizeNewlines(await readFile(outputPath, "utf8"));
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== "ENOENT") {
      throw error;
    }
  }

  if (current === expected) {
    continue;
  }

  drifted.push(relative(root, outputPath));
  if (!checkOnly) {
    await mkdir(dirname(outputPath), { recursive: true });
    await writeFile(outputPath, expected, "utf8");
  }
}

if (drifted.length === 0) {
  console.log("Protobuf consumers match proto/svc.proto.");
} else if (checkOnly) {
  console.error("Generated protobuf consumers are stale:");
  for (const path of drifted) {
    console.error(`  - ${path}`);
  }
  console.error("Run: bun run proto:gen");
  process.exitCode = 1;
} else {
  console.log("Generated protobuf consumers:");
  for (const path of drifted) {
    console.log(`  - ${path}`);
  }
}
